### ISSUE TITLE
Data Source styles are inconsistent

### ISSUE THREAD

**Issue by easherma** [datamade/justice-divided#83]
![source](https://cloud.githubusercontent.com/assets/10539855/26165356/4fa3e536-3af5-11e7-9c0f-c3d06c44d2cb.PNG)

This data source has a red underline. I think this style works fine for the body texts, but for these source links it ends up looking like its flagged as a spelling error.

![charts](https://cloud.githubusercontent.com/assets/10539855/26165560/0413fe16-3af6-11e7-9dc9-e6ea3a18c1a7.PNG)

Additionally, the data sources for the charts are _not_ underlined, and also don't have hyperlinks. IMO you should  have links to all the data sources, and either way the styling should be consistent.

**Comment by hancush** [comment]
The chart sources are not hyperlinks because scrolling with that many right-aligned links on mobile is too easy to fat finger and navigate away by accident. Instead, "Download the data buttons" are interspersed with the charts on desktop. 

I've updated the sparser, left-aligned source links to have a gray underline to ward off the spelling error connotation.

![demo](https://cloud.githubusercontent.com/assets/12176173/26166691/eec5556a-3af9-11e7-9a5e-d54a3c5f8d57.gif)

Thanks!
